### ISSUE TITLE
Error: HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by fgdrf** [jwgmeligmeyling/spotbugs-github-action#30]
I used spotbugs-githuib-action in udig-platform project worklow right after the maven build:

```
    - name: Run uDig product & sdk build (parallel)
      run: mvn install -B -Pproduct,sdk,test -DskipTests spotbugs:check --fail-at-end -T4
    - uses: jwgmeligmeyling/spotbugs-github-action@v1.2
      with:
        path: '**/spotbugsXml.xml'
```

spotbugsXml.xml are generated (checked locally) but I get http-errors. Proviously I testetd with version from master `uses: jwgmeligmeyling/spotbugs-github-action@master` but sometimes I got the same errors

see https://github.com/locationtech/udig-platform/pull/550/checks?check_run_id=3847205371#step:10:243

Any ideas whats going wrong?
